!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 200.0
maxOut: 173.0
minIn: 54.0
minOut: 5.0
pin: '9'
rest: 133.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
