!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 165.0
maxOut: 180.0
minIn: 15.0
minOut: 56.0
pin: '9'
rest: 65.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
