!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 130.0
maxOut: 155.0
minIn: 50.0
minOut: 44.0
pin: '8'
rest: 98.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
