!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 200.0
maxOut: 180.0
minIn: 65.0
minOut: 28.0
pin: '5'
rest: 133.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
