!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 165.0
maxOut: 169.0
minIn: 15.0
minOut: 0.0
pin: '5'
rest: 88.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
