!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 130.0
maxOut: 124.0
minIn: 50.0
minOut: 8.0
pin: '4'
rest: 99.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
