!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 200.0
maxOut: 170.0
minIn: 63.0
minOut: 0.0
pin: '13'
rest: 133.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
