!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 130.0
maxOut: 153.0
minIn: 50.0
minOut: 28.0
pin: '12'
rest: 90.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
