!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: false
maxIn: 180.0
maxOut: 168.0
minIn: 50.0
minOut: 14.0
pin: '14'
rest: 50.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
