!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 200.0
maxOut: 178.0
minIn: 50.0
minOut: 7.0
pin: '1'
rest: 133.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
