!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
autoStartPeers: true
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 130.0
maxOut: 136.0
minIn: 50.0
minOut: 37.0
pin: '0'
rest: 94.0
speed: 272.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
