!!org.myrobotlab.service.config.ServoConfig
autoDisable: false
clip: true
controller: Back
enabled: true
idleTimeout: 3000
inverted: true
maxIn: 180.0
maxOut: 167.0
minIn: 50.0
minOut: 21.0
pin: '2'
rest: 50.0
speed: 175.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
